V4
elasticio/maester-client pull request #29
Opened 2022-06-15 11:29 UTC by EmptyInfinity

2022-06-15 13:27 UTC, if0s approved these changes

2022-06-15 13:32 UTC, EmptyInfinity commented on package.json
> +    "aws-sdk": "2.1152.0",
oops

2022-06-21 15:43 UTC, if0s approved these changes

2022-06-23 07:57 UTC, if0s approved these changes

2022-07-07 09:58 UTC, EmptyInfinity commented
> **Platform team requirements:**
> 
- [x] 1. Nightly tests in CI.
- [x] 2. Disable dev dependencies check during audit.
- [x] 3. Version should adhere to semver rules. Breaking change - new major version.
- [x] 4. All tests from `object-storage-client` must be present here. Especially which cover some edge cases (like passing the same stream on retry). 
(Passing same stream could be covered only with [positive test](https://github.com/elasticio/maester-client/blob/v4/spec/StorageClient.spec.ts#L64))
- [x] 5. Exponential back-off like in `object-storage-client`.
(Because of having ability to config "delay on retry" was implemented logic like [this](https://github.com/elasticio/maester-client/blob/v4/src/utils.ts#L42))
- [ ] 6. All errors should be handled like in latest `object-storage-client`. Now they don't. E.g. I don't see Client error handler.
(Error handling were left as it is, you may familiar with handling approach in [integration-tests](https://github.com/elasticio/maester-client/blob/v4/spec-integration/ObjectStorage.spec.ts#L183))

Now related to how our services are using the lib 
- [x] 1. We should be able to create an instance to make add/update/delete requests. The instance should accept maester uri and jwtSecret.
- [x] 2. Each method that modifies DB object should accept `ttl`. `ttl` can have `-1` value.
- [x] 3. There should be ability to add stream for encrypt/decrypt.
- [x] 4. There should be ability to GET object as stream with specified jwt payload.
- [x] 5. There should be ability to PUT as stream with retries: 0.
- [x] 6. There should be ability to PUT with custom ttl and contentType (we get it from webhook request headers).
 (currently, there is no way to pass custom contentType, because it's [calculated automatically](https://github.com/elasticio/maester-client/blob/v4/src/StorageClient.ts#L22))
- [x] 7. There should be ability to POST a json object.
- [x] 8. There should be ability to GET object as json object.
([ObjectStorage](https://github.com/elasticio/maester-client/blob/v4/src/ObjectStorage.ts#L68) will return a string. And [ObjectStorageWrapper](https://github.com/elasticio/maester-client/blob/v4/src/ObjectStorageWrapper.ts#L63) will return parsed object (this class is designed to work with JSON objects)
- [x] 9. There should be ability to DELETE an object by ID.

2022-07-11 09:06 UTC, PaulAnnekov commented
Can you provide an example on how to override `Content-Type` for `update`?

2022-07-11 09:22 UTC, PaulAnnekov requested changes

2022-07-11 09:22 UTC, PaulAnnekov commented on src/utils.ts
> +export const getDelayTime = (retryDelay: number, currentReties: number): number => {
Please, read about exponential backoff and use it instead. You can check in monorepo how we implemented it for our version of the lib.

2022-07-11 09:22 UTC, PaulAnnekov commented on src/StorageClient.ts
> +        if (err?.response?.status < 500) throw e; // The request was made and the server responded with a status code
Just use "validateStatus: null", because you validate it manually, you don't need the help of axios.

2022-07-11 09:22 UTC, PaulAnnekov commented on README.md
> +This library propose you two clients: `ObjectStorage` & `ObjectStorageWrapper`.
It's nice to have a section about how to handle errors. You can check small section in our lib for reference.

2022-07-12 08:21 UTC, PaulAnnekov requested changes

2022-07-12 08:21 UTC, PaulAnnekov commented on .circleci/config.yml
> +      - image: cimg/node:16.16.0
No, 12.3.0. It should work under nodejs 12.3.0

2022-07-12 08:21 UTC, PaulAnnekov commented on src/interfaces.ts
> +  'content-type'?: string;
it will be nice to see it as exported const too, as TTL

2022-08-08 14:39 UTC, merged